### ISSUE TITLE
IFC Export Folder does not Exist

### ISSUE THREAD

**Issue by MaxSchultze** [dd-bim/City2BIM#4]
Beim Exportieren des Umgebungsmodelles zu IFC (siehe Bild 1) wird der Ordner nicht gefunden. Und es kommt die Fehlermeldung (siehe Bild 2).

Der Ordner existiert aber denn da liegt auch die Revit Datei drin.
![revit_ifc_export](https://user-images.githubusercontent.com/77496361/104813944-8b9b6180-580c-11eb-8682-9db0804db62e.PNG)
![revit_ifc_export2](https://user-images.githubusercontent.com/77496361/104813947-8fc77f00-580c-11eb-9246-bce39160442b.PNG)

Es wurde schon getestet diverse andere Ordner auszuwählen und auch die Namen zu ändern.

**Comment by Hutsimbl** [comment]
Export folder was hardcoded should be fixed now
