### ISSUE TITLE
CityGML import - parameter fieldName is not acceptable

### ISSUE THREAD

**Issue by Moschi87** [dd-bim/City2BIM#49]
We got new workstations and installed City2BIM for Revit 2021. Every time we try to import a CityGML file we get the following error message:

![Revit_exception_fieldName_not_acceptable](https://user-images.githubusercontent.com/93882138/178278234-2421b8f4-bb37-4499-a196-ae6908f68329.png)

Can someone check if this is a bug? We can reproduce the exception on multiple workstations (Windows 10 and Windows 11 with latest updates).
(The installations on our old workstations worked well and without any problems)

**Comment by Moschi87** [comment]
Thank you for the fast answer.

It happens with all GML files. Since we are from Saxony too we often have to deal with the CityGML data from Saxony:
https://www.geodaten.sachsen.de/downloadbereich-digitale-3d-stadtmodelle-4875.html

No need to use a special file for testing. There are no ä, ö or ü in the filenames. I can also confirm the error with the same files which worked before on the old workstation. Maybe your Addin needs some older package of .NET or something like this? But to me the error sounds like Revit API itself is unhappy with some names.

I will drop you an email tomorrow if you want to call me for further information.

**Comment by Hutsimbl** [comment]
I can confirm the issue with the fieldnames.

CityGML files from saxony contain 2 attributes with hyphens. It seems, this character is not allowed in field names for the extensible storages in Revit.

If I change the attribute names in the CityGML file from

- Stand_Basis-DLM to **Stand_Basis_DLM**
- Stand_3D-Stadtmodell to **Stand_3D_Stadtmodell**

the import works.

Maybe you can use this as a quick workaround?

**Comment by Hutsimbl** [comment]
hopefully resolved with #50 and #51 
new [release uploaded](https://github.com/dd-bim/City2BIM/releases/tag/v1.6.2)
