### ISSUE TITLE
Einladen verschiedener CityGML Kacheln

### ISSUE THREAD

**Issue by MaxSchultze** [dd-bim/City2BIM#5]
Die Rostocker Daten liefern Kacheln vom Vermessungsamt.
Diese sich einzeln einwandfrei einzuladen.
Das Einladen aller Kacheln in ein Projekt ist dabei jedoch nicht möglich. Bei dem Einladen einer weiteren Kachel scheint der Prozess abgeschlossen (Revit lässt sich weiter bedienen). Es ist jedoch weiterhin die zuerst eingeladene Kachel zu sehen. Eine Fehlermeldung wird nicht ausgegeben.

**Comment by Hutsimbl** [comment]
Should be resolved by now
